name: checar_coneccao_plugin
description: Plugin dart para verificar o status da conecção do dispositivo.
version: 1.1.4
homepage: https://github.com/pwlimaverde/checar_coneccao_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  return_success_or_error: ^0.1.5
  connectivity: ^3.0.2
  
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: ^0.0.1-dev.10
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.vorfast.checar_coneccao_plugin
        pluginClass: ChecarConeccaoPlugin
      ios:
        pluginClass: ChecarConeccaoPlugin